% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Untitled},
  pdfauthor={Group 30},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Untitled}
\author{Group 30}
\date{2022-11-18}

\begin{document}
\maketitle

\hypertarget{assignment-3.-logistic-regression-and-basis-function-expansion}{%
\subsection{Assignment 3. Logistic regression and basis function
expansion}\label{assignment-3.-logistic-regression-and-basis-function-expansion}}

The data file \textbf{pima-indians-diabetes.csv} contains information
about the onset of diabetes within 5 years in Pima Indians given medical
details. The variables are (in the same order as in the dataset):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Number of times pregnant.\\
\item
  Plasma glucose concentration a 2 hours in an oral glucose tolerance
  test.\\
\item
  Diastolic blood pressure (mm Hg).\\
\item
  Triceps skinfold thickness (mm).\\
\item
  2-Hour serum insulin (mu U/ml).\\
\item
  Body mass index (weight in kg/(height in m)\^{}2).\\
\item
  Diabetes pedigree function.\\
\item
  Age (years).\\
\item
  Diabetes (0=no or 1=yes)
\end{enumerate}

1.Make a scatterplot showing a Plasma glucose concentration on Age where
observations are colored by Diabetes levels. Do you think that Diabetes
is easy to classify by a standard logistic regression model that uses
these two variables as features? Motivate your answer.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_PIdiabetes }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"pima{-}indians{-}diabetes.csv"}\NormalTok{, }\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{9}\NormalTok{))}

\NormalTok{data\_PIdiabetes}\SpecialCharTok{$}\NormalTok{X9 }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(data\_PIdiabetes}\SpecialCharTok{$}\NormalTok{X9)}

\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data\_PIdiabetes, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ X8, }\AttributeTok{y =}\NormalTok{ X2, }\AttributeTok{colour =}\NormalTok{ X9)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Age (years)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Plasma glucose concentration"}\NormalTok{, }\AttributeTok{colour  =} \StringTok{"Diabetes (0=no or 1=yes)"}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\includegraphics{donni508_files/figure-latex/3.1-1.pdf}

\begin{itemize}
\tightlist
\item
  Yes! Motivation: Looking at the plot, one can see that the plasma
  glucose concentration is more higher for the group with Diabetes level
  1 compared to those with level 0. This is more evident when plasma
  glucose concentration is 150 or higher. At such one can conclude that
  it will be easy to classify Diabetes by a standard logistic regression
\end{itemize}

2.Train a logistic regression model with \(y\) = Diabetes as target
\(x_1\) = Plasma glucose concentration and \(x_2\) = Age as features and
make a prediction for all observations by using \(r\) = 0.5 as the
classification threshold. Report the probabilistic equation of the
estimated model (i.e., how the target depends on the features and the
estimated model parameters probabilistically). Compute also the training
misclassification error and make a scatter plot of the same kind as in
step 1 but showing the predicted values of Diabetes as a color instead.
Comment on the quality of the classification by using these results

\begin{itemize}
\tightlist
\item
  Logistic regression analysis belongs to the class of generalized
  linear models. In R generalized linear models are handled by the glm()
  function. The function is written as glm(response \textasciitilde{}
  predictor, family = binomial(link = ``logit''), data). Please note
  that logit is the default for binomial; thus, we do not have to type
  it explicitly. The glm() function returns a model object, therefore we
  may apply extractor functions, such as summary(), fitted() or predict,
  among others, on it. However, please note that the output numbers are
  on the logit scale. To actually predict probabilities we need to
  provide the predict() function an additional argument type =
  ``response''
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# X2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test.}
\CommentTok{\# X8. Age (years).}
\CommentTok{\# X9. Diabetes (0=no or 1=yes).}

\NormalTok{glm\_diabete }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(X9 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ X2 }\SpecialCharTok{+}\NormalTok{ X8, data\_PIdiabetes, }\AttributeTok{family =}\NormalTok{ binomial)}

\NormalTok{fit }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{fitted}\NormalTok{(glm\_diabete) }\SpecialCharTok{\textgreater{}=} \FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{glm\_diabete}\SpecialCharTok{$}\NormalTok{coefficients}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## (Intercept)          X2          X8 
## -5.89785793  0.03558250  0.02450157
\end{verbatim}

\begin{itemize}
\tightlist
\item
  we have \[g(x) = \cfrac{1}{1 + e^{-\theta^T x}} \] and use
  coefficients we got:
  \[g(x) = \cfrac{1}{1 + e^{-(-5.89785793 + 0.03558250x_1 + 0.02450157x_2)}} \]
  while \(x_1\) = Plasma glucose concentration and \(x_2\) = age.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tq1 }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(fit, data\_PIdiabetes}\SpecialCharTok{$}\NormalTok{X9)}
\NormalTok{tq1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
## fit   0   1
##   0 436 140
##   1  64 127
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# confusion matrix}
\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (}\FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(tq1)) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(tq1))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2659713
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# misclassification error}


\NormalTok{data\_PIdiabetes\_q1 }\OtherTok{\textless{}{-}}\NormalTok{ data\_PIdiabetes}
\NormalTok{data\_PIdiabetes\_q1}\SpecialCharTok{$}\NormalTok{X10 }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(fit)}

\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data\_PIdiabetes\_q1, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ X8, }\AttributeTok{y =}\NormalTok{ X2, }\AttributeTok{colour =}\NormalTok{ X10)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Age (years)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Plasma glucose concentration"}\NormalTok{, }\AttributeTok{colour =} \StringTok{"Predicted Diabetes (0=no or 1=yes)"}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\includegraphics{donni508_files/figure-latex/3.2 misclassification\&plot-1.pdf}

\begin{itemize}
\tightlist
\item
  From the glm model, Both Plasma glucose and Age have a significant
  influence on Diabetes. From the results of this classification, we can
  see that our misclassification error is about 26.6\%. This is not too
  bad I think. Just as seen with the original plot earlier, the plot
  with the predicted Diabetes also depits that level-1 Diabetes have
  more plasma glucose compare to level-0 group
\end{itemize}

3.Use the model estimated in step 2 to a) report the equation of the
decision boundary between the two classes b) add a curve showing this
boundary to the scatter plot in step 2. Comment whether the decision
boundary seems to catch the data distribution well.

\begin{itemize}
\tightlist
\item
  when r = 0.5, we have \[\cfrac{1}{1 + e^{-\theta^T x}} = 0.5\] then we
  have \(\theta^T x = 0\) ,
  i.e.~\(\theta_0 + \theta_1x_1 + \theta_2x_2 =0\)
  (\(x_1: concentration, x_2: age\))\\
  thus \(slope = \cfrac{-\theta_2}{\theta_1}\),
  \(intercept = \cfrac{-\theta_0}{\theta_1}\)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{theta }\OtherTok{\textless{}{-}} \FunctionTok{coef}\NormalTok{(glm\_diabete)}

\NormalTok{slope }\OtherTok{\textless{}{-}}\NormalTok{ (}\SpecialCharTok{{-}}\NormalTok{theta[}\DecValTok{3}\NormalTok{]) }\SpecialCharTok{/}\NormalTok{ theta[}\DecValTok{2}\NormalTok{]}
\NormalTok{intercept }\OtherTok{\textless{}{-}}\NormalTok{ (}\SpecialCharTok{{-}}\NormalTok{theta[}\DecValTok{1}\NormalTok{] ) }\SpecialCharTok{/}\NormalTok{ (theta[}\DecValTok{2}\NormalTok{]) }

\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data\_PIdiabetes\_q1, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ X8, }\AttributeTok{y =}\NormalTok{ X2, }\AttributeTok{colour =}\NormalTok{ X10)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =}\NormalTok{ slope, }\AttributeTok{intercept =}\NormalTok{ intercept) }\SpecialCharTok{+}
  
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Age (years)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Plasma glucose concentration"}\NormalTok{, }\AttributeTok{colour  =} \StringTok{"Predicted Diabetes (0=no or 1=yes)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{donni508_files/figure-latex/3.3-1.pdf}

\begin{itemize}
\tightlist
\item
  Comments:I think this decision boundary does well for separating the
  data belonging two classes, even though not all data are put into the
  right sides of the boundary line.
\end{itemize}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  Make same kind of plots as in step 2 but use thresholds r = 0.2 and r
  = 0.8. By using these plots, comment on what happens with the
  prediction when r value changes.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_r02 }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{fitted}\NormalTok{(glm\_diabete) }\SpecialCharTok{\textgreater{}=} \FloatTok{0.2}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}

\NormalTok{tr02 }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(fit\_r02, data\_PIdiabetes}\SpecialCharTok{$}\NormalTok{X9)}
\NormalTok{tr02}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        
## fit_r02   0   1
##       0 238  25
##       1 262 242
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#confusion matrix}
\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (}\FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(tr02)) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(tr02))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3741851
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#misclassification error}


\NormalTok{data\_PIdiabetes\_r02 }\OtherTok{\textless{}{-}}\NormalTok{ data\_PIdiabetes}
\NormalTok{data\_PIdiabetes\_r02}\SpecialCharTok{$}\NormalTok{X10 }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(fit\_r02)}

\NormalTok{slope }\OtherTok{\textless{}{-}}\NormalTok{ (}\SpecialCharTok{{-}}\NormalTok{theta[}\DecValTok{3}\NormalTok{]) }\SpecialCharTok{/}\NormalTok{ theta[}\DecValTok{2}\NormalTok{]}
\NormalTok{intercept }\OtherTok{\textless{}{-}}\NormalTok{ (}\SpecialCharTok{{-}}\FunctionTok{log}\NormalTok{(}\DecValTok{4}\NormalTok{) }\SpecialCharTok{{-}}\NormalTok{ theta[}\DecValTok{1}\NormalTok{] ) }\SpecialCharTok{/}\NormalTok{ (theta[}\DecValTok{2}\NormalTok{]) }

\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data\_PIdiabetes\_r02, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ X8, }\AttributeTok{y =}\NormalTok{ X2, }\AttributeTok{colour =}\NormalTok{ X10)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =}\NormalTok{ slope, }\AttributeTok{intercept =}\NormalTok{ intercept) }\SpecialCharTok{+}
  
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Age (years)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Plasma glucose concentration"}\NormalTok{, }\AttributeTok{colour  =} \StringTok{"Predicted Diabetes (0=no or 1=yes)"}\NormalTok{, }\AttributeTok{title =} \StringTok{"r = 0.2"}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\includegraphics{donni508_files/figure-latex/3.4 r0.2-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{fit\_r08 }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{fitted}\NormalTok{(glm\_diabete) }\SpecialCharTok{\textgreater{}=} \FloatTok{0.8}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}


\NormalTok{tr08 }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(fit\_r08, data\_PIdiabetes}\SpecialCharTok{$}\NormalTok{X9)}
\NormalTok{tr08}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##        
## fit_r08   0   1
##       0 490 231
##       1  10  36
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#confusion matrix}
\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (}\FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(tr08)) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(tr08))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.3142112
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#misclassification error}

\NormalTok{data\_PIdiabetes\_r08 }\OtherTok{\textless{}{-}}\NormalTok{ data\_PIdiabetes}
\NormalTok{data\_PIdiabetes\_r08}\SpecialCharTok{$}\NormalTok{X10 }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(fit\_r08)}

\NormalTok{slope }\OtherTok{\textless{}{-}}\NormalTok{ (}\SpecialCharTok{{-}}\NormalTok{theta[}\DecValTok{3}\NormalTok{]) }\SpecialCharTok{/}\NormalTok{ theta[}\DecValTok{2}\NormalTok{]}
\NormalTok{intercept }\OtherTok{\textless{}{-}}\NormalTok{ (}\FunctionTok{log}\NormalTok{(}\DecValTok{4}\NormalTok{) }\SpecialCharTok{{-}}\NormalTok{ theta[}\DecValTok{1}\NormalTok{] ) }\SpecialCharTok{/}\NormalTok{ (theta[}\DecValTok{2}\NormalTok{]) }

\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data\_PIdiabetes\_r08, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ X8, }\AttributeTok{y =}\NormalTok{ X2, }\AttributeTok{colour =}\NormalTok{ X10)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{slope =}\NormalTok{ slope, }\AttributeTok{intercept =}\NormalTok{ intercept) }\SpecialCharTok{+}
  
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Age (years)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Plasma glucose concentration"}\NormalTok{, }\AttributeTok{colour  =} \StringTok{"Predicted Diabetes (0=no or 1=yes)"}\NormalTok{, }\AttributeTok{title =} \StringTok{"r = 0.8"}\NormalTok{ )}
\end{Highlighting}
\end{Shaded}

\includegraphics{donni508_files/figure-latex/3.4 r0.8-1.pdf}

\begin{itemize}
\tightlist
\item
  Comment: When r is 0.8, we can find that the method is more likely to
  regard the patients with diabetes as healthy. The probability is 87\%.
  By contrast, when we use r = 0.2 as the threshold, we can find the
  patients with more probability, which is 91\%.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{242}\SpecialCharTok{/}\NormalTok{(}\DecValTok{242}\SpecialCharTok{+}\DecValTok{25}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.906367
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DecValTok{231}\SpecialCharTok{/}\NormalTok{(}\DecValTok{231}\SpecialCharTok{+}\DecValTok{36}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.8651685
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{4}
\tightlist
\item
  Perform a basis function expansion trick by computing new features
  \(z_1 = x_1^4, z_2 = x_1^3x_2^1, z_3 = x_1^2x_2^2, z_4 = x_1^1x_2^3, z_5 = x_2^4\),
  adding them to the data set and then computing a logistic regression
  model with 𝑦𝑦 as target and \(x_1, x_2, z_1, …,z_5\) as features.
  Create a scatterplot of the same kind as in step 2 for this model and
  compute the training misclassification rate. What can you say about
  the quality of this model compared to the previous logistic regression
  model? How have the basis expansion trick affected the shape of the
  decision boundary and the prediction accuracy?
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{data\_PIdiabetes\_q5 }\OtherTok{\textless{}{-}}\NormalTok{  data\_PIdiabetes }\SpecialCharTok{\%\textgreater{}\%}  \FunctionTok{select}\NormalTok{(}\FunctionTok{c}\NormalTok{(X2,X8,X9))}
\CommentTok{\# X2,X8,X9}
\CommentTok{\# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test.}
\CommentTok{\# 8. Age (years).}
\CommentTok{\# 9. Diabetes (0=no or 1=yes).}

\NormalTok{data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{Z1 }\OtherTok{\textless{}{-}}\NormalTok{ data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{X2}\SpecialCharTok{\^{}}\DecValTok{4}
\NormalTok{data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{Z2 }\OtherTok{\textless{}{-}}\NormalTok{ data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{X2}\SpecialCharTok{\^{}}\DecValTok{3} \SpecialCharTok{*}\NormalTok{ data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{X8}\SpecialCharTok{\^{}}\DecValTok{1}
\NormalTok{data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{Z3 }\OtherTok{\textless{}{-}}\NormalTok{ data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{X2}\SpecialCharTok{\^{}}\DecValTok{2} \SpecialCharTok{*}\NormalTok{ data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{X8}\SpecialCharTok{\^{}}\DecValTok{2}
\NormalTok{data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{Z4 }\OtherTok{\textless{}{-}}\NormalTok{ data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{X2}\SpecialCharTok{\^{}}\DecValTok{1} \SpecialCharTok{*}\NormalTok{ data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{X8}\SpecialCharTok{\^{}}\DecValTok{3}
\NormalTok{data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{Z5 }\OtherTok{\textless{}{-}}\NormalTok{ data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{X8}\SpecialCharTok{\^{}}\DecValTok{3}

\NormalTok{glm\_diabete\_q5 }\OtherTok{\textless{}{-}} \FunctionTok{glm}\NormalTok{(X9 }\SpecialCharTok{\textasciitilde{}}\NormalTok{ X2 }\SpecialCharTok{+}\NormalTok{ X8 }\SpecialCharTok{+}\NormalTok{ Z1 }\SpecialCharTok{+}\NormalTok{ Z2 }\SpecialCharTok{+}\NormalTok{ Z3 }\SpecialCharTok{+}\NormalTok{ Z4 }\SpecialCharTok{+}\NormalTok{ Z5, data\_PIdiabetes\_q5, }\AttributeTok{family =}\NormalTok{ binomial)}

\NormalTok{fit }\OtherTok{\textless{}{-}} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{fitted}\NormalTok{(glm\_diabete\_q5) }\SpecialCharTok{\textgreater{}=} \FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}

\NormalTok{tq5 }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(fit, data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{X9)}
\NormalTok{tq5}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    
## fit   0   1
##   0 434 118
##   1  66 149
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# confusion matrix}
\DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (}\FunctionTok{sum}\NormalTok{(}\FunctionTok{diag}\NormalTok{(tq5)) }\SpecialCharTok{/} \FunctionTok{sum}\NormalTok{(tq5))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2398957
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# misclassification error}

\NormalTok{data\_PIdiabetes\_q5}\SpecialCharTok{$}\NormalTok{X10 }\OtherTok{\textless{}{-}} \FunctionTok{factor}\NormalTok{(fit)}

\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data\_PIdiabetes\_q5, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ X8, }\AttributeTok{y =}\NormalTok{ X2, }\AttributeTok{colour =}\NormalTok{ X10)) }\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Age"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Plasma glucose concentration"}\NormalTok{, }\AttributeTok{colour  =} \StringTok{"Predicted Diabetes (0=no or 1=yes)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{donni508_files/figure-latex/3.5-1.pdf}

\begin{itemize}
\tightlist
\item
  Comment: When we increase the number of inputs and r equals 0.5, the
  eventual value of misclassification rate is similar to the one in the
  second question. The boundary line is no longer a straight line but a
  curve.
\end{itemize}

\end{document}
