---
title: "Untitled"
author: "Group 30"
date: "2022-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment 3. Logistic regression and basis function expansion

```{r 3.1}
library(tidyverse)
library(ggplot2)

data_PIdiabetes <- read.csv("D:/Program/Git/Repo/732A99-MachineLearning/lab01/Assignment3/pima-indians-diabetes.csv", col.names = c(1:9))

# 1. Number of times pregnant.
# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test.
# 3. Diastolic blood pressure (mm Hg).
# 4. Triceps skinfold thickness (mm).
# 5. 2-Hour serum insulin (mu U/ml).
# 6. Body mass index (weight in kg/(height in m)^2).
# 7. Diabetes pedigree function.
# 8. Age (years).
# 9. Diabetes (0=no or 1=yes).

data_PIdiabetes$X9 <- factor(data_PIdiabetes$X9)

ggplot(data = data_PIdiabetes, aes(x = X8, y = X2, colour = X9)) + 
  geom_point() + 
  labs(x = "Age (years)", y = "Plasma glucose concentration", colour  = "Diabetes (0=no or 1=yes)" )

```


```{r 3.2 split}
set.seed(24601)

n <- nrow(data_PIdiabetes)

r_train <- sample(1:n, floor(n*0.5))
train <-  data_PIdiabetes[r_train, ]

r_nont <- setdiff(1:n, r_train)
r_valid <- sample(r_nont, floor(n*0.25))
valid <- data_PIdiabetes[r_valid, ]
 
test <- data_PIdiabetes[setdiff(r_nont, r_valid), ]

```

```{r 3.2 train}
# 2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test.
# 8. Age (years).
# 9. Diabetes (0=no or 1=yes).

glm_diabete <- glm(X9 ~ X2 + X8, train, family = binomial)

fit <- ifelse(fitted(glm_diabete) >= 0.5, 1, 0)


```

```{r 3.2 probabilistic equation}
#WTF?
```

```{r 3.2 misclassification&plot}

Misclass(fit, train$X9)

train_q1 <- train
train_q1$X10 <- factor(fit)

ggplot(data = train_q1, aes(x = X8, y = X2, colour = X10)) + 
  geom_point() + 
  labs(x = "Age (years)", y = "Plasma glucose concentration", colour  = "Predicted Diabetes (0=no or 1=yes)" )


```

```{r 3.3}
theta <- coef(glm_diabete)
#theta1 + theta2 x1 + theta3 x2  == 0.5

slope <- (-theta[2]) / theta[3]
intercept <- (0.5 - theta[1] ) / (theta[3]) 

ggplot(data = train_q1, aes(x = X8, y = X2, colour = X10)) + 
  geom_point() + 
  geom_abline(slope = slope, intercept = intercept) +
  #geom_abline(slope = slope + 0.15, intercept = intercept - 18.5) +
  labs(x = "Age (years)", y = "Plasma glucose concentration", colour  = "Predicted Diabetes (0=no or 1=yes)" )


```

